import React from "react";
import ServicesCard from "./_components/cards/ServicesCard";
import ContainerPage from "@/components/container/page";
import { getAllServices } from "@/services/servicesAction";

// const getAllServices = async () => {
//   const res = await fetch(`http://localhost:3000/api/server`);

//   await new Promise((reslove) =>
//     setTimeout(() => {
//       reslove();
//     }, 3000)
//   );

//   const data = await res.json();

//   return data;
// };

export const metadata = {
  title: {
    default: "Services",
    template: "%s | Care Plus",
  },
  description: "Generated by create next app",
};

const Servicespage = async () => {
  const services = await getAllServices();
  return (
    <div>
      <ContainerPage>
        <h2>Servicespage</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2  md:grid-cols-3 lg:grid-cols-4 ">
          {services.map((service) => {
            return (
              <ServicesCard key={service._id} service={service}></ServicesCard>
            );
          })}
        </div>
      </ContainerPage>
    </div>
  );
};

export default Servicespage;
