import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";



const poppins = Poppins(
  {
    weight:["100","200","400", "500", "600", "800"]
  }
);



export const metadata = {
  title:{
    default:"Care Plus",
    template:"%s | Care Plus"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={[poppins.className, "antialiased"].join(" ")}
      >
       

        <main className="py-2 min-h-screen">

        {children}
        </main>
        
      </body>
    </html>
  );
}
