import Services from '@/components/home/Services';
import React from 'react';


export const metadata = {
  title:"All Services",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <Services></Services>
            
        </div>
    );
};

export default page;